# see https://s.apache.org/asfyaml
github:
  description: "Apache Maven Doxia Sitetools"
  homepage: https://maven.apache.org/doxia/doxia-sitetools
  labels:
    - java
    - build-management
    - apache-maven
    - maven
    - doxia
